### PR TITLE
support custom id prefixes

### PR DESCRIPTION
**Pull request by flosse**

### CODE REVIEW

**Comment by Ede123** [comment]
>> I guess you'll have reasons you need this;)

>of course! Now I'm just waiting for v0.28 to be released ;-)

@flosse Care to share? It's just that I can't imagine a single reason why it would be useful to prefix all IDs with a fixed string.
I'm currently working on the Inkscape extension of Scour and I'm considering to leave this option out of the UI, but if you can convince me it could be useful for people I'll obviously add it.

**Comment by su-v** [comment]
@Ede123 - here's one example explaining a need for prefixed identifiers:
http://lists.cairographics.org/archives/cairo/2015-October/026523.html

**Comment by Ede123** [comment]
@su-v Thanks, good example!

I already added the option anyway (without convincing being necessary ;-)) and it's in my [merge request on Launchpad](https://code.launchpad.net/~eduard-braun2/inkscape/scour/+merge/278387) waiting to be merged into the Inkscape codebase.

**Comment by codedread** [comment]
@flosse FYI I've updated my site to point over here now!

**Pull request merged**
