### PR TITLE
Basic implementation for Travis CI

### PR DESCRIPTION
**Pull request by Ede123**
Here's a very basic implementation to use Travis CI, since it is time to tackle #31 to prevent glitches like #51 in future.

In principle it already works as tested in [my fork](https://github.com/Ede123/scour). So far it installs Scour, checks the installation by calling `scour --version` and runs `testscour.py`.
For example the initial build of master [failed](https://travis-ci.org/Ede123/scour/jobs/120202729), but my dummy pull request made it [pass](https://travis-ci.org/Ede123/scour/builds/120206007).

This is not (yet) meant to be a final PR, but to start discussion on what should be implemented (I'm just getting started with CI myself and am learning as I go), so let me know what you think.
On the other hand it seems to me even this basic functionality is already a big help and we probably don't even need much more...

### CODE REVIEW

**Comment by oberstet** [comment]
CI is highly welcome!! Thanks for working on that.

FWIW, a common way to do CI in Python project nowerdays probably is using a combination of Tox and Travis. Eg see https://github.com/crossbario/txaio - maybe have a quick peek into that, as it is doing things "very clean" and follows Python best-practices generally in many ways.

**Comment by Ede123** [comment]
I will have a look at it (given that you don't shoot it down until it looks exactly like you imagined... then you'd better implement it yourself).

**Comment by Ede123** [comment]
OK, I updated the PR. Does basically the same thing as before but this time using tox.
Latest test run with those files is [here](https://travis-ci.org/Ede123/scour/builds/120307796).

Let me know what you think...

**Comment by oberstet** [comment]
@Ede123 awesome! a good start.

**Pull request merged**
