### PR TITLE
Allow the Scour module to be used as a standalone program

### PR DESCRIPTION
**Pull request by Ede123**
This PR allows to use the Scour module as a "standalone program" (e.g. download, unzip and run) without the need to install the module itself and/or any third party modules.

It consists of two parts:
* Use a local copy of "six". We should not expect six to be available in the users Python environment. E.g. Inkscape comes with a minimal installation of Python that does neither include six nor allows the user to easily install it.
* Add a simple wrapper script around the Scour module that can be executed directly. The relative imports introduced in d1c66cc75bbe474b5a45a7cd45ed27207311d897 have broken the previous approach to achieve this with `if __name__ == '__main__': run()`

### CODE REVIEW

**Comment by oberstet** [comment]
No, copy-pasting an external dependency (six) into this module is an anti-pattern ..

**Comment by Ede123** [comment]
I don't like it either, but I like the external dependency even less... Do you have a better idea?

Would you accept a minimum set of compatibility code to replace "six" altogether?
Granted, "six" is a small module, but even a small module seems a bit excessive for a module as "simple" as Scour.

**Comment by oberstet** [comment]
As said, duplicating code from a well established external package is a no go.

Rgd the wrapper script: that's already there https://github.com/codedread/scour/blob/master/setup.py#L49

**Comment by Ede123** [comment]
I wasn't suggesting duplicating. I just think that what we currently try to achieve with "six" can be done with much less code in a much easier way. However if you're in favor of an external dependency let's stick to it and see how things play out.

Regarding wrapper script: This script is only created when installing the module, right?
This part of the PR request was specifically for the case where one *does not* want to install the module (e.g. for development purposes or to run multiple versions of Scour side-by-side on the same system). As a matter of fact I did all my recent development using this wrapper and as #9 indicates this could come in handy for others, too.
Do you have any reason why we shouldn't add it?

**Comment by oberstet** [comment]
> This script is only created when installing the module, right?

Yes. It's a feature of distutils.

For development purposes, you can start scour like `python -m scour.run`.
For multiple versions of scour, there is virtualenv.

> Do you have any reason why we shouldn't add it?

Yes: there is an established approach: distutils / console_scripts.

**Comment by Ede123** [comment]
> For development purposes, you can start scour like python -m scour.run
I figured that out, too, but only after I searched the Internet on how to do it. It's not an obvious/intuitive solution.

It might well be that your suggested approach is established amongst Python professionals (which you seem to be), but it surely complicates usage of Scour for everybody else.

Personally I always prefer software that keeps it as simple as running a single script/executable and does not need any additional steps like setup / installation of external libraries, etc so it's readily available for everybody (without a deeper understanding of e.g. Python / distutils / console_scripts / pip / whatever)
Maybe we simply differ in opinion here, but maybe it's also something for you to reconsider.

**Comment by oberstet** [comment]
> It might well be that your suggested approach is established

Yes, it is.

And "established" == "simple", because of expectations, info on the Web etc etc.

btw: you should be able to directly run the : `python scour/scour.py` also because of this

https://github.com/codedread/scour/blob/master/scour/scour.py#L3305

**Comment by Ede123** [comment]
> btw: you should be able to directly run the : python scour/scour.py also because of this

No, that specific code is actually broken after d1c66cc75bbe474b5a45a7cd45ed27207311d897 as mentioned in my initial description for this PR.
The linked commit introduced relative imports and trying to relatively import from a script does not work (one first has to import the parent module from an absolute path).
As I didn't find an easy way around this I decided on the wrapper script.

**Comment by oberstet** [comment]
Huh? The code is using absolute imports https://github.com/codedread/scour/blob/master/scour/scour.py#L52

**Comment by oberstet** [comment]
@Ede123 I've pushed https://pypi.python.org/pypi/scour/0.31

**Comment by Ede123** [comment]
> Huh? The code is using absolute imports

I think https://github.com/codedread/scour/blob/master/scour/scour.py#L59-L60 as well as https://github.com/codedread/scour/blob/master/scour/scour.py#L62 are relative imports, aren't they?

When trying to execute the module as a script those lines error out (with an error message stating that a relative import is not possible without the parent module being imported absolutely; I can give you the exact error message when I get home where I have access to a machine with python installed)

> I've pushed https://pypi.python.org/pypi/scour/0.31
Great!

**Comment by Ede123** [comment]
@oberstet: This is the error that is thrown when trying to execute the module as a script:
```
Traceback (most recent call last):
  File "scour.py", line 59, in <module>
    from .svg_regex import svg_parser
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by oberstet** [comment]
@Ede123 ah, right. could you retry with trunk pls? just pushed https://github.com/codedread/scour/commit/302f7f7477193165b2b1bdcd5997ee4e1acbf997

**Comment by Ede123** [comment]
I'm afraid this did not do it:
```
> python scour.py --version
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
AttributeError: 'module' object has no attribute '__path__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scour.py", line 59, in <module>
    from scour.svg_regex import svg_parser
  File "E:\Temp\Downloads\Scour\scour.git\scour\scour.py", line 59, in <module>
    from scour.svg_regex import svg_parser
ImportError: No module named 'scour.svg_regex'; 'scour' is not a package
```

**Comment by oberstet** [comment]
sure. try: `python scour/scour.py --version`. anyway: I won't change this. a package is a package.

**Comment by Ede123** [comment]
Exactly the same issue... Did you try that on your machine? If it works I assume it only works because you have the module installed?

**Comment by oberstet** [comment]
works.

```console
oberstet@thinkpad-t430s:~$ ./python279/bin/virtualenv ~/foobar
New python executable in /home/oberstet/foobar/bin/python
Installing setuptools, pip...done.
oberstet@thinkpad-t430s:~$ source ~/foobar/bin/activate
(foobar)oberstet@thinkpad-t430s:~$ which python
/home/oberstet/foobar/bin/python
(foobar)oberstet@thinkpad-t430s:~$ python
Python 2.7.9 (default, Jan 18 2015, 21:40:29) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scour
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named scour
>>> 
(foobar)oberstet@thinkpad-t430s:~$ which scour
/usr/local/bin/scour
(foobar)oberstet@thinkpad-t430s:~$ cd scm/oberstet/scour/
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ git pull
Already up-to-date.
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ make test_version
PYTHONPATH=. python -m scour.scour --version
Traceback (most recent call last):
  File "/home/oberstet/python279/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/oberstet/python279/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/oberstet/scm/oberstet/scour/scour/scour.py", line 60, in <module>
    from scour.svg_transform import svg_transform_parser
  File "scour/svg_transform.py", line 63, in <module>
    from six.moves import range
ImportError: No module named six.moves
make: *** [test_version] Fehler 1
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ which pip
/home/oberstet/foobar/bin/pip
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ pip install six
You are using pip version 6.0.6, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting six
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six

Successfully installed six-1.10.0
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ make test_version
PYTHONPATH=. python -m scour.scour --version
0.31
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ make test_help
PYTHONPATH=. python -m scour.scour --help
scour 0.31
Copyright Jeff Schiller, Louis Simard, 2010
Usage: scour.py [-i input.svg] [-o output.svg] [OPTIONS]

If the input/output files are specified with a svgz extension, then compressed
SVG is assumed. If the input file is not specified, stdin is used. If the
output file is not specified,  stdout is used.

Options:
  --version                   show program's version number and exit
  -h, --help                  show this help message and exit
  --disable-simplify-colors   won't convert all colors to #RRGGBB format
  --disable-style-to-xml      won't convert styles into XML attributes
  --disable-group-collapsing  won't collapse <g> elements
  --create-groups             create <g> elements for runs of elements with
                              identical attributes
  --enable-id-stripping       remove all un-referenced ID attributes
  --enable-comment-stripping  remove all <!-- --> comments
  --shorten-ids               shorten all ID attributes to the least number of
                              letters possible
  --shorten-ids-prefix=SHORTEN_IDS_PREFIX
                              shorten all ID attributes with a custom prefix
  --disable-embed-rasters     won't embed rasters as base64-encoded data
  --keep-unreferenced-defs    won't remove elements within the defs container
                              that are unreferenced
  --keep-editor-data          won't remove Inkscape, Sodipodi or Adobe
                              Illustrator elements and attributes
  --remove-metadata           remove <metadata> elements (which may contain
                              license metadata etc.)
  --renderer-workaround       work around various renderer bugs (currently
                              only librsvg) (default)
  --no-renderer-workaround    do not work around various renderer bugs
                              (currently only librsvg)
  --strip-xml-prolog          won't output the <?xml ?> prolog
  --enable-viewboxing         changes document width/height to 100%/100% and
                              creates viewbox coordinates
  -p DIGITS, --set-precision=DIGITS
                              set number of significant digits (default: 5)
  -q, --quiet                 suppress non-error output
  --indent=INDENT_TYPE        indentation of the output: none, space, tab
                              (default: space)
  --nindent=INDENT_DEPTH      depth of the indentation, i.e. number of
                              spaces/tabs: (default: 1)
  --no-line-breaks            do not create line breaks in output (also
                              disables indentation; might be overriden by
                              xml:space="preserve")
  --strip-xml-space           strip the xml:space="preserve" attribute from
                              the root SVG element
  --protect-ids-noninkscape   Don't change IDs not ending with a digit
  --protect-ids-list=PROTECT_IDS_LIST
                              Don't change IDs given in a comma-separated list
  --protect-ids-prefix=PROTECT_IDS_PREFIX
                              Don't change IDs starting with the given prefix
(foobar)oberstet@thinkpad-t430s:~/scm/oberstet/scour$ 
```

**Pull request closed without merging**
